services:
  backend:
    image: backend
    container_name: backend
    env_file:
      - ./expensy_backend/.env
    ports:
      - "8706:8706"
    networks:
      - final-project-devops

  frontend:
    image: frontend
    container_name: frontend
    env_file:
      - ./expensy_frontend/.env.production
    ports:
      - "3000:3000"
    networks:
      - final-project-devops

  mongo:
    image: mongo:latest
    container_name: mongo
    env_file:
      - ./expensy_backend/.env
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - final-project-devops

  redis:
    image: redis:latest
    container_name: redis
    env_file:
      - ./expensy_backend/.env    
    ports:
      - "6379:6379"
    command: redis-server --requirepass someredispassword
    networks:
      - final-project-devops

networks:
  final-project-devops:
    driver: bridge

volumes:
  mongo-data:
